#!/bin/bash
# Installs tmux and sets up its configuration.
#
# Caleb Foust

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TMUX_CONF="$HOME/.tmux.conf"
OT_CONF="$HOME/.oakthree.conf"

ensure_link "$THIS_DIR/main.conf" "$TMUX_CONF"
ensure_link "$THIS_DIR/oakthree.conf" "$OT_CONF"

install_tmux() {
  $grab libevent-dev

  # The release for tmux 2.5
  RELEASE_URL="https://github.com/tmux/tmux/releases/download/2.5/tmux-2.5.tar.gz"

  cd /tmp
  wget $RELEASE_URL
  tar xf tmux-2.5.tar.gz
  cd tmux-2.5
  ./configure && make
  sudo make install
}

TMUX_DIR="$HOME/.tmux"
if [ ! -d "$TMUX_DIR" ]; then
  # Install the TMUX plugin manager.
  git clone https://github.com/tmux-plugins/tpm "$TMUX_DIR/plugins/tpm"
  "$TMUX_DIR/plugins/tpm/bin/install_plugins"
fi

if missing "tmux"; then
  install_tmux
elif ! tmux -V | grep -q "2.5"; then
  install_tmux
fi
