#!/bin/bash
# Installs tmux and sets up its configuration.
#
# Caleb Foust

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TMUX_CONF="$HOME/.tmux.conf"
OT_CONF="$HOME/.oakthree.conf"

rm "$TMUX_CONF"

if [ ! -L "$TMUX_CONF" ]; then
  ln -s "$THIS_DIR/main.conf" "$TMUX_CONF"
fi

if [ ! -L "$OT_CONF" ]; then
  ln -s "$THIS_DIR/oakthree.conf" "$OT_CONF"
fi

install_tmux() {
  $grab libevent-dev

  # The release for tmux 2.5
  RELEASE_URL="https://github.com/tmux/tmux/releases/download/2.5/tmux-2.5.tar.gz"

  cd /tmp
  wget $RELEASE_URL
  tar xf tmux-2.5.tar.gz
  cd tmux-2.5
  ./configure && make
  sudo make install
}

TMUX_DIR="$HOME/.tmux"
if [ ! -d "$TMUX_DIR" ]; then
  # Install the TMUX plugin manager.
  git clone https://github.com/tmux-plugins/tpm "$TMUX_DIR/plugins/tpm"
  "$TMUX_DIR/plugins/tpm/bin/install_plugins"
fi

if ! [ -x "$(command -v tmux)" ]; then
  install_tmux
else
  if ! tmux -V | grep -q "2.5"; then
    install_tmux
  fi
fi
