#!/bin/bash
# Installs tmux and sets up its configuration.
#
# Caleb Foust

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TMUX_CONF="$HOME/.tmux.conf"
OT_CONF="$HOME/.oakthree.conf"

ensure_link "$THIS_DIR/main.conf" "$TMUX_CONF"
ensure_link "$THIS_DIR/oakthree.conf" "$OT_CONF"
ensure_link "$THIS_DIR/snclirc" "$HOME/.snclirc"

install_tmux() {
  grab libevent-dev libncurses5-dev libncursesw5-dev locales-all

  # The release for tmux 2.5
  RELEASE_URL="https://github.com/tmux/tmux/releases/download/2.5/tmux-2.5.tar.gz"

  cd /tmp
  wget $RELEASE_URL
  tar xf tmux-2.5.tar.gz
  cd tmux-2.5
  ./configure && make
  _sudo make install
}

if missing "tmux"; then
  install_tmux
elif ! tmux -V | grep -q "2.5"; then
  install_tmux
fi

TMUX_DIR="$HOME/.tmux"
TPM_DIR="$TMUX_DIR/plugins/tpm"

if [ ! -d "$TPM_DIR" ]; then
  # Install the TMUX plugin manager.
  git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"
fi

OAKTHREE_DIR="$DEV_DIR/cfoust/tmux-oakthree"
if [ ! -d "$OAKTHREE_DIR" ]; then
  git clone https://github.com/cfoust/tmux-oakthree.git "$OAKTHREE_DIR"
fi
ensure_link "$OAKTHREE_DIR" "$TMUX_DIR/plugins/tmux-oakthree"

"$TMUX_DIR/plugins/tpm/bin/install_plugins"

if ! missing "pip3" && missing "sncli"; then
  pip3 install sncli
fi

SNCLI_FILE="$THIS_DIR/.sncli-pass"
if [[ ! -f "$SNCLI_FILE" ]]; then
  echo "You must make your .sncli-pass file."
fi
