#!/bin/bash
#
# Installs everything necessary for my command-line dev environment.

set -x

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$BASE_DIR/common.sh"

$apt update

# We need git from the git-go
ensure_package "git"

if in_gitpod; then
  # Check everything out over HTTPS because Gitpod doesn't support SSH yet
  git config --global 'url.https://github.com/.insteadOf' 'git@github.com:'
fi

# Clone this repo if it doesn't exist
if [ ! -d ~/cawnfig ]; then
  if in_gitpod; then
    ln -s ~/.dotfiles ~/cawnfig
    sudo chown -R gitpod:gitpod ~/.dotfiles
  else
    git clone https://github.com/cfoust/cawnfig.git ~/cawnfig
  fi
fi

# Create our lovely Developer directory
mkdir -p "$DEV_DIR"

git submodule update --init

# Run installers
install
