#!/bin/bash
#
# Installs everything for my ideal X windows setup including i3 and keynav.

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$BASE_DIR/common.sh"

mkdir -p ~/Screenshots

if missing_package "fonts-powerline"; then
  $grab fonts-powerline
fi

BACKGROUND_DIR="$HOME/Backgrounds"
mkdir -p "$BACKGROUND_DIR"

if [ ! -f "$BACKGROUND_DIR/1 - SjQprDK.jpg" ]; then
  wget -q https://www.dropbox.com/s/v2hj2pdq7fst3ex/wallpapers.zip?dl=0 -O /tmp/wallpapers.zip
  unzip -q /tmp/wallpapers.zip -d "$BACKGROUND_DIR"
fi

if missing "xsel"; then
  $grab xsel
fi

# Hasklig!
HASKLIG_URL="https://github.com/i-tu/Hasklig/releases/download/1.1/Hasklig-1.1.zip"
if [ ! -f "/usr/share/fonts/opentype/Hasklig-Regular.otf" ]; then
  wget -q "$HASKLIG_URL" -O /tmp/hasklig.zip
  unzip -q /tmp/hasklig.zip -d "/usr/share/fonts/opentype"
fi

install "x"
