#!/bin/bash
# Installs vim from source configured with Python3 interpolation.
#
# Caleb Foust

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

VIM_DIR="$HOME/.vim"

# Symlink our vim config
ensure_link "$THIS_DIR" "$VIM_DIR"

mkdir -p "$VIM_DIR/tmp"

install_vim() {
  if in_gitpod; then
    # the vim version in apt is fine
    grab vim
    return
  fi

  VIM_DEPS="libncurses5-dev libatk1.0-dev libbonoboui2-dev "
  VIM_DEPS+="libcairo2-dev python3-dev "
  VIM_DEPS+="git"

  # Make sure we have all of vim's dependencies
  grab $VIM_DEPS

  cd /tmp
  if in_gitpod; then
    wget https://cawnfig.s3.us-west-2.amazonaws.com/vim-14113fdf9-061223.tar.gz
    tar xf vim-14113fdf9-061223.tar.gz
    cd vim
    LDFLAGS=-rdynamic ./configure --with-features=huge \
      --enable-multibyte \
      --enable-python3interp \
      --with-python3-command=python3.11 \
      --with-python3-config-dir=$HOME/.pyenv/versions/3.11.1/lib/python3.11/config-3.11-x86_64-linux-gnu \
      --enable-fail-if-missing \
      --enable-cscope --prefix=/usr
  else
    git clone https://github.com/vim/vim.git
    cd vim
    git checkout 14113fdf9cb3d588c0d1c3a210246b981cf5aad3
    ./configure --with-features=huge \
      --enable-multibyte \
      --enable-python3interp=yes \
      --enable-fail-if-missing \
      --enable-cscope --prefix=/usr
  fi

  make VIMRUNTIMEDIR=/usr/share/vim/vim90

  _sudo make install
}

# Only install if the version is below 8
  install_vim

if [ ! -f "$VIM_DIR/autoload/plug.vim" ] ; then
  grab curl
  curl -fLo "$VIM_DIR/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Need ag for CtrlP
ensure_package "silversearcher-ag"

# Install all of our plugins
vim -c :PlugInstall -c :qa

if in_gitpod && ! missing 'npm'; then
  npm i -g prettier
fi
