#!/usr/bin/env bash
# Pads whatever you pass to STDIN with enough spaces to center it on the
# screen. Uses `tput` to get the terminal's width.  Does not do any padding if
# the input is wider than the shell.

input="$(cat /dev/stdin)"
columns="$(tput cols)"

# Sometimes I like bash. This is not one of those times.
# This checks the max length of the line and adds padding if necessary.
declare -i max
max=0
max=$(echo "$input" | ( while read line; do
  length="${#line}"

  if [ "$length" -gt "$max" ]; then
    max="$length"
  fi
  done
  echo "$max" ))

# Don't pad if the input is too wide.
if [ "$max" -gt "$columns" ]; then
  echo "$input"
  exit 0
fi

padding=$(expr $columns - $max)
padding=$(expr $padding / 2)

padding_str=""
for ((n=0;n<$padding;n++)); do padding_str+=" "; done

echo "$input" | sed "s/^/$padding_str/"
