#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if missing "konsole"; then
  $apt update
  $grab konsole
fi

ensure_link "$THIS_DIR/share" "$HOME/.local/share/konsole"
ensure_link "$THIS_DIR/konsolerc" "$HOME/.config/konsolerc"

FONTS_DIR="/usr/local/share/fonts"
IOSEVKA_ZIP="$THIS_DIR/../../binaries/06-iosevka-term-slab-1.14.1.zip"

# Install Iosevka fonts
if ! [ -f "$FONTS_DIR/ttf/iosevka-term-slab-thin.ttf" ]; then
  sudo unzip "$IOSEVKA_ZIP" -d "$FONTS_DIR"
  sudo fc-cache -fv
fi
