#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ensure_package "konsole"

ensure_link "$THIS_DIR/share" "$HOME/.local/share/konsole"
ensure_link "$THIS_DIR/konsolerc" "$HOME/.config/konsolerc"

FONTS_DIR="/usr/local/share/fonts"
IOSEVKA_ZIP="$THIS_DIR/../../binaries/06-iosevka-term-slab-1.14.1.zip"

# Install Iosevka fonts
if ! [ -f "$FONTS_DIR/ttf/iosevka-term-slab-thin.ttf" ]; then
  sudo unzip "$IOSEVKA_ZIP" -d "$FONTS_DIR"
  sudo fc-cache -fv
fi

ITERM_SCHEMES="$CAWNFIG_DIR/submodules/iTerm2-Color-Schemes/konsole"

# Verify all of the theme files are linked
for scheme in $ITERM_SCHEMES/*.colorscheme; do
  [ -e "$item" ] || continue
  name=$(basename "$scheme")
  src="$scheme"
  dest="$THIS_DIR/share/$name"

  if [ -f "$dest" ]; then
    rm "$dest"
  fi

  # Hard link intentional
  ln "$src" "$dest"
done

generate_themes_list() {
  local themes
  themes=$(ls -1 "$CAWNFIG_DIR/submodules/iTerm2-Color-Schemes/konsole")
  themes=$(echo "$themes" | while read theme; do
  echo $(basename "$theme" .colorscheme)
done)
  echo -e "$themes" > $THIS_DIR/share/themelist
}

generate_themes_list
