#!/bin/bash
# Adds our bash config to bashrc if it
# isn't already included.
#
# Caleb Foust

if ! [ -x "$(command -v fzf)" ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install --key-bindings --completion --update-rc
fi

CF_BASH_CONF="~/cawnfig/bash/config.sh"

if cat ~/.bashrc | grep -q "$CF_BASH_CONF"; then
  echo 'bashrc already includes special config.'
  exit
fi

echo "source $CF_BASH_CONF" >> ~/.bashrc
