#!/bin/bash
#
# Installs Vundle, the plugin manager for vim.

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$BASE_DIR/common.sh"

if [ ! -d ~/.vim/autoload/plug.vim ] ; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Need ag for CtrlP
if ! [ -x "$(command -v ag)" ]; then
  $grab silversearcher-ag
fi

# Install all of our plugins
vim -c :PlugInstall -c :qa
