#!/bin/bash
# Installs tmux and sets up its configuration.
#
# Caleb Foust
source common.sh

rm ~/.tmux.conf
ln -s ~/cawnfig/tmux/main.conf ~/.tmux.conf

$APT libevent-dev

# The release for tmux 2.5
RELEASE_URL="https://github.com/tmux/tmux/releases/download/2.5/tmux-2.5.tar.gz"

cd /tmp
wget $RELEASE_URL
tar xf tmux-2.5.tar.gz
cd tmux-2.5
./configure && make
sudo make install

# Install tpm if necessary
if [ ! -d "$HOME/.tmux" ]; then
  # Install the TMUX plugin manager.
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ~/.tmux/plugins/tpm/bin/install_plugins
fi
