#!/bin/bash
# All of the fun stuff I use on Lubuntu. Probably would work
# just fine on Ubuntu too.
# Caleb Foust
source common.sh

if ! [ -x "$(command -v i3)" ]; then
  $APT i3
  mkdir -p ~/.config/i3
  ln -s ~/cawnfig/i3/config ~/.config/i3/config
fi

if ! [ -x "$(command -v konsole)" ]; then
  sudo apt-get update
  $APT konsole
fi

# Keynav to navigate with the keyboard
if ! [ -x "$(command -v keynav)" ]; then
  $APT keynav
  ln -s ~/cawnfig/keynav/keynavrc ~/.keynavrc
fi
