#!/bin/bash
# Installs tmux and sets up its configuration.
#
# Caleb Foust
source common.sh

rm ~/.tmux.conf

if [ ! -L ~/.tmux.conf ]; then
  ln -s ~/cawnfig/tmux/main.conf ~/.tmux.conf
fi

if [ ! -L ~/.oakthree.conf ]; then
  ln -s ~/cawnfig/tmux/oakthree.conf ~/.oakthree.conf
fi

install_tmux() {
  $APT libevent-dev

  # The release for tmux 2.5
  RELEASE_URL="https://github.com/tmux/tmux/releases/download/2.5/tmux-2.5.tar.gz"

  cd /tmp
  wget $RELEASE_URL
  tar xf tmux-2.5.tar.gz
  cd tmux-2.5
  ./configure && make
  sudo make install
}

if [ ! -d ~/.tmux ]; then
  # Install the TMUX plugin manager.
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ~/.tmux/plugins/tpm/bin/install_plugins
fi

if ! [ -x "$(command -v tmux)" ]; then
  install_tmux
else
  if ! tmux -V | grep -q "2.5"; then
    install_tmux
  fi
fi
