#!/bin/bash
# All of the fun stuff I use on Lubuntu. Probably would work
# just fine on Ubuntu too.
# Caleb Foust
source common.sh

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if ! [ -x "$(command -v i3)" ]; then
  $APT i3
  mkdir -p ~/.config/i3
  ln -s ~/cawnfig/i3/config ~/.config/i3/config
fi

if ! [ -x "$(command -v konsole)" ]; then
  sudo apt-get update
  $APT konsole
fi

FONTS_DIR="/usr/local/share/fonts"

# Install Iosevka fonts
if ! [ -f "$FONTS_DIR/ttf/iosevka-term-slab-thin.ttf" ]; then
  sudo unzip "$SCRIPT_DIR/../binaries/06-iosevka-term-slab-1.14.1.zip" -d "$FONTS_DIR"
  fc-cache -fv
fi

# Keynav to navigate with the keyboard
if ! [ -x "$(command -v keynav)" ]; then
  $APT keynav
  ln -s ~/cawnfig/keynav/keynavrc ~/.keynavrc
fi

if ! [ -f "$HOME/.Xmodmap" ]; then
  ln -s ~/cawnfig/xmodmap/config ~/.Xmodmap
fi
