#!/bin/bash
# All of the fun stuff I use on Lubuntu. Probably would work
# just fine on Ubuntu too.
# Caleb Foust
source common.sh

if ! [ -x "$(command -v i3)" ]; then
  $APT i3
  mkdir -p ~/.config/i3
  ln -s ~/cawnfig/i3/config ~/.config/i3/config
fi

if ! [ -x "$(command -v terminator)" ]; then
  sudo add-apt-repository -y ppa:gnome-terminator/ppa
  sudo apt-get update
  $APT terminator
  mkdir -p ~/.config/terminator
  ln -s ~/cawnfig/terminator/config ~/.config/terminator/config
fi

# Keynav to navigate with the keyboard
if ! [ -x "$(command -v keynav)" ]; then
  $APT keynav
  ln ~/cawnfig/keynav/keynavrc ~/.keynavrc
fi
