#!/bin/bash
# Adds our bash config to bashrc if it
# isn't already included.
#
# Caleb Foust

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$BASE_DIR/common.sh"

mkdir -p ~/Developer/cfoust

if ! [ -x "$(command -v fzf)" ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install --key-bindings --completion --update-rc
else
  no_need 'install fzf'
fi

if [ ! -d "$HOME/.dolly" ]; then
  git clone git@github.com:cfoust/dolly.git ~/Developer/cfoust/dolly
  ln -s ~/Developer/cfoust/dolly ~/.dolly
else
  no_need 'install dolly'
fi

CF_BASH_CONF="~/cawnfig/bash/config.sh"

if cat ~/.bashrc | grep -q "$CF_BASH_CONF"; then
  no_need 'add special config to bashrc'
else
  echo "source $CF_BASH_CONF" >> ~/.bashrc
fi
