#!/bin/bash
# Installs YouCompleteMe, which Vundle can't handle on its own.
#
# Caleb Foust
source common.sh

YCMDIR=~/.vim/bundle/YouCompleteMe
cd $YCMDIR
$APT build-essential cmake python-dev python3-dev

if [ ! -f $YCMDIR/third_party/ycmd/ycm_core.so ] ; then
  # I'm not a fan of most of the completers as I really just look
  # to YCM for fuzzy identifier matching.
  ./install.py --clang-completer
fi
