#!/bin/bash
# Installs vim from source configured with Python3 interpolation.
#
# Caleb Foust

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$BASE_DIR/common.sh"

# Kind of silly to still have this in as it's almost always empty,
# but here we go
touch ~/.vimprivate

# Symlink our vim config
if [ ! -d ~/.vim ] ; then
  echo 'Symlinked vimrc.'
  ln -s ~/cawnfig/vim ~/.vim
  mkdir ~/.vim/tmp
else
  no_need 'symlink vimrc'
fi

# Only install if the version is below 8
if vim --version | grep -q "Vi IMproved 8."; then
  no_need 'install the newest vim'
else
  VIM_DEPS="libncurses5-dev libgnome2-dev libgnomeui-dev "
  VIM_DEPS+="libgtk2.0-dev libatk1.0-dev libbonoboui2-dev "
  VIM_DEPS+="libcairo2-dev libx11-dev libxpm-dev libxt-dev "
  VIM_DEPS+="python3-dev ruby-dev lua5.1 lua5.1-dev libperl-dev "
  VIM_DEPS+="git"

  # Make sure we have all of vim's dependencies
  $grab $VIM_DEPS

  cd /tmp
  git clone https://github.com/vim/vim.git
  cd vim
  ./configure --with-features=huge \
    --enable-multibyte \
    --enable-rubyinterp=yes \
    --enable-python3interp=yes \
    --with-python3-config-dir=/usr/lib/python3.5/config \
    --enable-perlinterp=yes \
    --enable-luainterp=yes \
    --enable-gui=gtk2 --enable-cscope --prefix=/usr

  make VIMRUNTIMEDIR=/usr/share/vim/vim80
  sudo make install
fi
