#!/bin/bash
# Installs Vundle, the plugin manager for vim.
#
# Caleb Foust
source common.sh

if [ ! -d ~/.vim/bundle/Vundle.vim ] ; then
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

# Need ag for CtrlP
$APT silversearcher-ag

# Install all of our plugins
vim -c :PluginInstall -c :qa
