#!/bin/bash
# Install a custom VSCode extension if this is in Gitpod

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if in_gitpod; then
  cd "$THIS_DIR/autovim"
  yarn install
  npm install -g vsce
  vsce package -o autovim.vsix
  gitpod-code --install-extension "$(pwd)/autovim.vsix"
fi
