#!/bin/bash
# Install a custom VSCode extension if this is in Gitpod

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Cancel this for now, it's not working
if in_gitpod; then
  cd "$THIS_DIR/autovim"
  yarn install
  yarn vscode:prepublish
  ensure_link "/workspace/.vscode-remote/extensions/undefined.autovim-0.0.1" "$THIS_DIR/autovim"
fi
