#!/bin/bash
# Install a custom VSCode extension if this is in Gitpod

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Cancel this for now, it's not working
if false; then
  cd "$THIS_DIR/autovim"
  yarn install
  npm install -g vsce
  vsce package -o autovim.vsix
  "$THIS_DIR/wait-for-it.sh" 127.0.0.1:23000
  gitpod-code --install-extension "$(pwd)/autovim.vsix"
fi
