#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

URXVT_PATH="/usr/local/bin/urxvt"

if ! [ -x "$URXVT_PATH" ]; then
  tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
  cd "$tmp_dir"
  git clone https://github.com/exg/rxvt-unicode.git
  cd rxvt-unicode
  ./configure

  grab curl
  LIBPTYTTY_VERSION="libptytty-1.8"
  curl -o libptytty.tar.gz "http://dist.schmorp.de/libptytty/$LIBPTYTTY_VERSION.tar.gz"
  tar xvf libptytty.tar.gz
  mv "$LIBPTYTTY_VERSION" libptytty

  LIVEV_VERSION="libev-4.33"
  curl -o libev.tar.gz "http://dist.schmorp.de/libev/libev-4.33.tar.gz"
  tar xvf libev.tar.gz
  mv "$LIVEV_VERSION" libev

  make
  _sudo make install
fi

ensure_link "$THIS_DIR/config" "$HOME/.Xdefaults"
