#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ensure_package "xcb-proto"
ensure_package "libxcb-ewmh-dev"
ensure_package "python-xcbgen"

if missing "polybar"; then
  cd /tmp
  git clone --recursive https://github.com/jaagr/polybar
  mkdir polybar/build
  cd polybar/build
  cmake ..
  sudo make install
fi

mkdir -p "$HOME/.config/polybar"
ensure_link "$THIS_DIR/config" "$HOME/.config/polybar/config"
